server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: userdemo
          uri: lb://service-userdemo
          predicates:
            - Path=/users/**
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/orders/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info
