server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - RequestSize=10MB
        - Retry=5,series=SERVER_ERROR,methods=GET
        - CircuitBreaker=name=cbDefault,fallbackUri=forward:/__fallback
        - RemoveRequestHeader=Cookie
        - AddResponseHeader=X-Gateway,msa-skeleton
      routes:
        - id: userdemo
          uri: lb://service-userdemo
          predicates:
            - Path=/users/**
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/orders/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: health,info

